# This file is managed by Qt Creator, do not edit!

set("CMAKE_CXX_FLAGS" "-DQT_QML_DEBUG" CACHE "STRING" "" FORCE)
set("CMAKE_CXX_FLAGS_DEBUG" "-g -DQT_QML_DEBUG" CACHE "STRING" "" FORCE)
set("CMAKE_CXX_FLAGS_RELWITHDEBINFO" "-O2 -g -DNDEBUG -DQT_QML_DEBUG" CACHE "STRING" "" FORCE)